CREATE OR REPLACE PACKAGE BODY PKG_CM_MAINTENANCE AS
/*
  - 시노님 생성, 없으면 자동 생성
  - 동작 실패, 쓰지 마셔용, 프로시저에서는 다른 유저 테이블 정보를 볼수 없음
*/
PROCEDURE CREATE_SYNONYM IS
  CURSOR C_LIST 
    IS
    SELECT OWNER, TABLE_NAME
    FROM ALL_TABLES 
    WHERE TABLE_NAME IN (
      SELECT TABLE_NAME FROM ALL_TABLES
      MINUS
      SELECT TABLE_NAME FROM ALL_SYNONYMS
    )
    AND LENGTH( OWNER ) = 2 AND TABLE_NAME LIKE OWNER || '_%'
    ;    
    
  BEGIN

    DBMS_OUTPUT.PUT_LINE( 'START' );
    
    FOR C_L IN C_LIST LOOP
      DBMS_OUTPUT.PUT_LINE( C_L.OWNER || ', ' || C_L.TABLE_NAME );
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE( 'END' );

  END;
   
END PKG_CM_MAINTENANCE;