CREATE OR REPLACE PACKAGE PKG_CM_MAINTENANCE AS
    PROCEDURE CREATE_SYNONYM; -- 동작실패, 쓰지 마셔용
END PKG_CM_MAINTENANCE;

/*
SELECT OWNER, TABLE_NAME
FROM ALL_ALL_TABLES 
WHERE TABLE_NAME IN (
  SELECT TABLE_NAME FROM ALL_ALL_TABLES
  MINUS
  SELECT TABLE_NAME FROM USER_CATALOG WHERE TABLE_TYPE = 'SYNONYM'
)
AND LENGTH( OWNER ) = 2 AND TABLE_NAME LIKE OWNER || '_%'
;
*/