SELECT * FROM TT_ONE_TABLE ORDER BY SEQ DESC;

UPDATE TT_ONE_TABLE SET t_date = sysdate - 364;

DELETE FROM TT_ONE_TABLE WHERE SEQ <> 20;

SELECT LENGTH( T_BLOB ) FROM TT_ONE_TABLE ORDER BY SEQ DESC;

COMMIT;

SELECT * FROM TT_ONE_TABLE_V;
INSERT INTO TT_ONE_TABLE( SEQ, T_VARCHAR, T_DATE, T_CLOB, T_BLOB ) VALUES ( TT_ONE_TABLE_S.nextval, '테스트 '|| SYSDATE, SYSDATE, 'CLOB.......', NULL );

SELECT '테스트 입니다' AS V_VARCHAR FROM TT_ONE_TABLE_V;

SELECT '테스트 입니다' AS v_Varchar, 1 AS seq FROM Tt_One_Table_V;