USE [MUNDI];

DROP TABLE TEST_1;
DROP TABLE TEST_3;
DROP TABLE TEST_2;

CREATE TABLE TEST_1(
  SEQ NUMERIC(16)
  , ENG_USER_NM NVARCHAR(128)
  , INS_DT DATE
  , INS_ID VARCHAR(30)
  , INS_OBJ NVARCHAR(128)
  , INS_IP VARCHAR(64)
  , UPD_DT DATE
  , UPD_ID VARCHAR(30)
  , UPD_OBJ NVARCHAR(128)
  , UPD_IP VARCHAR(64)
  , CONSTRAINT [PK_TEST_1]
    PRIMARY KEY CLUSTERED( 
      [SEQ]
    )
);

CREATE TABLE TEST_2(
  SEQ NUMERIC(16)
  , ENG_USER_NM NVARCHAR(128)
  , TEST_TEXT VARCHAR(MAX)
  , INS_DT DATE
  , INS_ID VARCHAR(30)
  , INS_OBJ NVARCHAR(128)
  , INS_IP VARCHAR(64)
  , UPD_DT DATE
  , UPD_ID VARCHAR(30)
  , UPD_OBJ NVARCHAR(128)
  , UPD_IP VARCHAR(64)
  , CONSTRAINT [PK_TEST_2]
    PRIMARY KEY CLUSTERED( 
      [SEQ]
    )
);

CREATE TABLE TEST_3(
  SEQ NUMERIC(16)
  , ENG_USER_NM NVARCHAR(128)
  , TEST_TEXT NVARCHAR(MAX)
  , TEST2_SEQ NUMERIC(16)
  , INS_DT DATE
  , INS_ID VARCHAR(30)
  , INS_OBJ NVARCHAR(128)
  , INS_IP VARCHAR(64)
  , UPD_DT DATE
  , UPD_ID VARCHAR(30)
  , UPD_OBJ NVARCHAR(128)
  , UPD_IP VARCHAR(64)
  , CONSTRAINT [PK_TEST_3]
    PRIMARY KEY CLUSTERED( 
      [SEQ]
    )
  , CONSTRAINT FK_TEST3_TEST2 FOREIGN KEY (TEST2_SEQ) 
    REFERENCES TEST_2 (SEQ) 
);