select * from cm_mkjava_meta_vi;

SELECT 
    COL.OWNER AS DB_NM
  , COL.TABLE_NAME AS TAB_NM
  , TCM.COMMENTS AS TAB_DESC
  , COL.COLUMN_NAME AS COL_NM 
  , CCM.COMMENTS AS COL_DESC
  , COL.DATA_TYPE AS COL_TYPE
  , COL.DATA_LENGTH AS COL_LEN
  , COL.DATA_PRECISION AS COL_PREC
  , COL.DATA_SCALE AS COL_SCALE
  , COL.NULLABLE AS COL_NULL
  , COL.COLUMN_ID AS COL_SEQ
  , NVL( (
      SELECT 'Y'
      FROM ALL_CONS_COLUMNS C, All_CONSTRAINTS A
      WHERE C.TABLE_NAME      = COL.TABLE_NAME
        AND C.COLUMN_NAME     = COL.COLUMN_NAME
        AND C.CONSTRAINT_NAME = A.CONSTRAINT_NAME
        AND C.TABLE_NAME      = A.TABLE_NAME        
        AND A.CONSTRAINT_TYPE = 'P'            
        ), 'N'
    ) AS IS_PK  --// PK여부
  , NVL( ( SELECT COUNT( C.COLUMN_NAME ) AS CNT
        FROM ALL_CONS_COLUMNS C, All_CONSTRAINTS A
        WHERE C.TABLE_NAME      = COL.TABLE_NAME
          AND C.COLUMN_NAME     = COL.COLUMN_NAME
          AND C.CONSTRAINT_NAME = A.CONSTRAINT_NAME
          AND C.TABLE_NAME      = A.TABLE_NAME        
          AND ( A.CONSTRAINT_TYPE = 'P' OR A.CONSTRAINT_TYPE = 'R' )
        GROUP BY C.COLUMN_NAME
      ), '0'
    ) AS R_CNT  --// 관계 타입
  , ( SELECT D.TABLE_NAME || ',' || D.COLUMN_NAME
      FROM ALL_CONS_COLUMNS C, All_CONSTRAINTS A, ALL_CONS_COLUMNS D
      WHERE C.TABLE_NAME      = COL.TABLE_NAME
        AND C.COLUMN_NAME     = COL.COLUMN_NAME
        AND C.CONSTRAINT_NAME = A.CONSTRAINT_NAME        
        AND A.CONSTRAINT_TYPE = 'R'
        AND A.R_CONSTRAINT_NAME = D.CONSTRAINT_NAME
    ) AS REF_TAB_N_COL
FROM ALL_TAB_COLUMNS COL
INNER JOIN ALL_TAB_COMMENTS TCM   -- 테이블 코멘트
  ON  COL.OWNER       = TCM.OWNER
  AND COL.TABLE_NAME  = TCM.TABLE_NAME
  AND TCM.TABLE_TYPE  = 'TABLE'
INNER JOIN ALL_COL_COMMENTS CCM   -- 컬럼 코멘트
  ON  COL.OWNER       = CCM.OWNER
  AND COL.TABLE_NAME  = CCM.TABLE_NAME
  AND COL.COLUMN_NAME = CCM.COLUMN_NAME
WHERE 'TT' LIKE '%' || COL.OWNER || '%'
ORDER BY COL.OWNER ASC, COL.TABLE_NAME ASC, COL.COLUMN_ID ASC
;

