--// 테이블 구조 조회
SELECT * FROM USER_CATALOG;
SELECT * FROM RESOWN.USER_TAB_COLUMNS;
SELECT * FROM ALL_COL_COMMENTS;   -- 컬럼 코멘트 조회
SELECT * FROM All_CONSTRAINTS;    -- 테이블로 CONSTRAINT_TYPE 구할수 있음
SELECT * FROM ALL_CONS_COLUMNS;   -- 컬럼 제약사항 구할 수 있음