/*
  만들어 져 있지 않은 시퀀스를 추가로 생성함
  실행 USER : MN
*/
DECLARE CURSOR C_LIST 
    IS
    SELECT OWNER, TABLE_NAME
    FROM ALL_TABLES 
    WHERE TABLE_NAME IN (
      SELECT TABLE_NAME FROM ALL_TABLES
      MINUS
      SELECT SUBSTR( SEQUENCE_NAME, 0, LENGTH( SEQUENCE_NAME ) - 2 )
      FROM USER_SEQUENCES
    )
    AND LENGTH( OWNER ) = 2 AND TABLE_NAME LIKE OWNER || '_%';
    
  BEGIN

    FOR C_L IN C_LIST LOOP
    
      EXECUTE IMMEDIATE 'CREATE SEQUENCE ' || C_L.TABLE_NAME || '_S START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE';
      
    END LOOP;    

  END;