CREATE TABLESPACE CM_TS DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\CM_TS.dbf' SIZE 100M AUTOEXTEND ON NEXT 50M;
CREATE USER CM IDENTIFIED BY 1234 DEFAULT TABLESPACE CM_TS;
GRANT CONNECT, RESOURCE TO CM;