/** USER : CM */
--// 권한관리 ▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣
DROP SEQUENCE CM_ROLE_MGR_S;
INSERT INTO CM_ROLE_MGR( SEQ, CO_CD, ROLE_NM, DSP_SEQ ) VALUES( 1, '0000', N'시스템관리자', 1 );
CREATE SEQUENCE CM_ROLE_MGR_S START WITH 2 INCREMENT BY 1 NOMAXVALUE NOCYCLE;

--// 권한그룹관리 ▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣
INSERT INTO CM_ROLEGRP_MGR( SEQ, CO_CD, ROLEGRP_NM, DSP_SEQ ) VALUES( CM_ROLEGRP_MGR_S.nextval, '0000', N'시스템관리그룹', 1 );

--// MAP : 권한관리-권한그룹관리 ▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣
INSERT INTO CM_ROLEROLEGRP_MAP( SEQ, ROLE_SEQ, ROLEGRP_SEQ ) VALUES( CM_ROLEGRP_MGR_S.nextval, ( SELECT SEQ FROM CM_ROLE_MGR WHERE ROLE_NM = N'시스템관리자' ), ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) );

--// 공통코드 : C = Common(공통) / S = Status(상태) ▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣
INSERT INTO CM_COMCD_MGR( SEQ, COM_GRP, GRP_NM, COM_CD, CD_NM ) VALUES( CM_COMCD_MGR_S.nextval, 'S101', N'사용여부', 'Y', N'사용' );
INSERT INTO CM_COMCD_MGR( SEQ, COM_GRP, GRP_NM, COM_CD, CD_NM ) VALUES( CM_COMCD_MGR_S.nextval, 'S101', N'사용여부', 'N', N'미사용' );

--// 사용자 : 비번 = 1( sha256 ) ▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣
INSERT INTO CM_USER_MGR (SEQ, ROLE_SEQ, CO_CD, LOGIN_ID, PWD, PWD_EX_DT, USER_NM, USE_YN, ACC_ST_DT, ACC_ED_DT )
VALUES( CM_USER_MGR_S.nextval, (
    SELECT SEQ FROM CM_ROLE_MGR WHERE ROLE_NM = N'시스템관리자'
  ), '0000', 'admin', '6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b', sysdate+99999, N'시스템관리자', '1', SYSDATE, SYSDATE+99999 );

--// 프로그램관리 ▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣
INSERT INTO CM_PGM_MGR( SEQ, PGM_NM ) VALUES( CM_PGM_MGR_S.nextval, N'Blank' );
INSERT INTO CM_PGM_MGR( SEQ, PGM_NM ) VALUES( CM_PGM_MGR_S.nextval, N'CM_메인' );
INSERT INTO CM_PGM_MGR( SEQ, PGM_NM ) VALUES( CM_PGM_MGR_S.nextval, N'CM_프로그램관리' );
INSERT INTO CM_PGM_MGR( SEQ, PGM_NM ) VALUES( CM_PGM_MGR_S.nextval, N'CM_메뉴관리' );
INSERT INTO CM_PGM_MGR( SEQ, PGM_NM ) VALUES( CM_PGM_MGR_S.nextval, N'CM_권한관리' );
INSERT INTO CM_PGM_MGR( SEQ, PGM_NM ) VALUES( CM_PGM_MGR_S.nextval, N'CM_시스템사용자관리' );

--// 메뉴 관리 ▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣
INSERT INTO CM_MENU_MGR( SEQ, PGM_SEQ, UP_SEQ, CO_CD, MENU_NM, DSP_SEQ ) VALUES( CM_MENU_MGR_S.nextval, ( SELECT SEQ FROM CM_PGM_MGR WHERE PGM_NM = N'Blank' ), NULL, '0000', N'시스템', 1 );

INSERT INTO CM_MENU_MGR( SEQ, PGM_SEQ, UP_SEQ, CO_CD, MENU_NM, DSP_SEQ ) VALUES( CM_MENU_MGR_S.nextval, ( SELECT SEQ FROM CM_PGM_MGR WHERE PGM_NM = N'Blank' ), ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템' AND UP_SEQ IS NULL ), N'시스템관리', 1 );
INSERT INTO CM_MENU_MGR( SEQ, PGM_SEQ, UP_SEQ, MENU_NM, DSP_SEQ ) VALUES( CM_MENU_MGR_S.nextval
  , ( SELECT SEQ FROM CM_PGM_MGR WHERE PGM_NM = N'CM_시스템사용자관리' )  --// 프로그램_SEQ
  , ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템관리' AND UP_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템' AND UP_SEQ IS NULL ) )  --// 상위메뉴_SEQ
  , N'시스템사용자관리' --// 프로그램명
  , 1 --// 정렬순서
);

INSERT INTO CM_MENU_MGR( SEQ, PGM_SEQ, UP_SEQ, CO_CD, MENU_NM, DSP_SEQ ) VALUES( CM_MENU_MGR_S.nextval, ( SELECT SEQ FROM CM_PGM_MGR WHERE PGM_NM = N'Blank' ), ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템' AND UP_SEQ IS NULL ), N'메뉴관리', 2 );
INSERT INTO CM_MENU_MGR( SEQ, PGM_SEQ, UP_SEQ, MENU_NM, DSP_SEQ ) VALUES( CM_MENU_MGR_S.nextval
  , ( SELECT SEQ FROM CM_PGM_MGR WHERE PGM_NM = N'CM_프로그램관리' )  --// 프로그램_SEQ
  , ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'메뉴관리' AND UP_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템' AND UP_SEQ IS NULL ) )  --// 상위메뉴_SEQ
  , N'프로그램관리' --// 프로그램명
  , 1 --// 정렬순서
);
INSERT INTO CM_MENU_MGR( SEQ, PGM_SEQ, UP_SEQ, CO_CD, MENU_NM, DSP_SEQ ) VALUES( CM_MENU_MGR_S.nextval
  , ( SELECT SEQ FROM CM_PGM_MGR WHERE PGM_NM = N'CM_메뉴관리' )     --// 프로그램_SEQ
  , ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'메뉴관리' ) --// 상위메뉴_SEQ
  , N'메뉴관리' --// 프로그램명
  , 2  --// 정렬순서
);
INSERT INTO CM_MENU_MGR( SEQ, PGM_SEQ, UP_SEQ, CO_CD, MENU_NM, DSP_SEQ ) VALUES( CM_MENU_MGR_S.nextval
  , ( SELECT SEQ FROM CM_PGM_MGR WHERE PGM_NM = N'CM_권한관리' )  --// 프로그램_SEQ
  , ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'메뉴관리' AND UP_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템' AND UP_SEQ IS NULL ) )  --// 상위메뉴_SEQ
  , N'권한관리' --// 프로그램명
  , 3 --// 정렬순서
);
INSERT INTO CM_MENU_MGR( SEQ, PGM_SEQ, UP_SEQ, CO_CD, MENU_NM, DSP_SEQ ) VALUES( CM_MENU_MGR_S.nextval
  , ( SELECT SEQ FROM CM_PGM_MGR WHERE PGM_NM = N'CM_권한관리' )  --// 프로그램_SEQ
  , ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'메뉴관리' AND UP_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템' AND UP_SEQ IS NULL ) )  --// 상위메뉴_SEQ
  , N'권한그룹관리' --// 프로그램명
  , 4 --// 정렬순서
);
INSERT INTO CM_MENU_MGR( SEQ, PGM_SEQ, UP_SEQ, CO_CD, MENU_NM, DSP_SEQ ) VALUES( CM_MENU_MGR_S.nextval
  , ( SELECT SEQ FROM CM_PGM_MGR WHERE PGM_NM = N'CM_권한관리' )  --// 프로그램_SEQ
  , ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'메뉴관리' AND UP_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템' AND UP_SEQ IS NULL ) )  --// 상위메뉴_SEQ
  , N'권한그룹별메뉴관리' --// 프로그램명
  , 5 --// 정렬순서
);
INSERT INTO CM_MENU_MGR( SEQ, PGM_SEQ, UP_SEQ, CO_CD, MENU_NM, DSP_SEQ ) VALUES( CM_MENU_MGR_S.nextval
  , ( SELECT SEQ FROM CM_PGM_MGR WHERE PGM_NM = N'CM_권한관리' )  --// 프로그램_SEQ
  , ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'메뉴관리' AND UP_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템' AND UP_SEQ IS NULL ) )  --// 상위메뉴_SEQ
  , N'사용자별메뉴관리' --// 프로그램명
  , 6 --// 정렬순서
);
--// 메뉴버튼 관리 ▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣
INSERT INTO CM_MENUBTN_MGR( SEQ, BTN_NM ) VALUES( CM_MENUBTN_MGR_S.nextval, N'조회' );
INSERT INTO CM_MENUBTN_MGR( SEQ, BTN_NM ) VALUES( CM_MENUBTN_MGR_S.nextval, N'신규' );
INSERT INTO CM_MENUBTN_MGR( SEQ, BTN_NM ) VALUES( CM_MENUBTN_MGR_S.nextval, N'삭제' );
INSERT INTO CM_MENUBTN_MGR( SEQ, BTN_NM ) VALUES( CM_MENUBTN_MGR_S.nextval, N'저장' );

--// MAP : 메뉴버튼-메뉴 ▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'시스템사용자관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'조회' ), 1 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'시스템사용자관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'신규' ), 2 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'시스템사용자관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'삭제' ), 3 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'시스템사용자관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'저장' ), 4 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'메뉴관리' AND UP_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템' AND UP_SEQ IS NULL ) ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'조회' ), 1 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'메뉴관리' AND UP_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템' AND UP_SEQ IS NULL ) ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'신규' ), 2 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'메뉴관리' AND UP_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템' AND UP_SEQ IS NULL ) ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'삭제' ), 3 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'메뉴관리' AND UP_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템' AND UP_SEQ IS NULL ) ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'저장' ), 4 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'권한관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'조회' ), 1 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'권한관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'신규' ), 2 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'권한관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'삭제' ), 3 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'권한관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'저장' ), 4 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'권한그룹관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'조회' ), 1 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'권한그룹관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'신규' ), 2 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'권한그룹관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'삭제' ), 3 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'권한그룹관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'저장' ), 4 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'권한그룹별메뉴관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'조회' ), 1 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'권한그룹별메뉴관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'신규' ), 2 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'권한그룹별메뉴관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'삭제' ), 3 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'권한그룹별메뉴관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'저장' ), 4 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'사용자별메뉴관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'조회' ), 1 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'사용자별메뉴관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'신규' ), 2 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'사용자별메뉴관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'삭제' ), 3 );
INSERT INTO CM_MENUBTN_MAP( SEQ, MENU_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_MENUBTN_MAP_S.nextval, ( SELECT SEQ FROM CM_MENU_MGR WHERE CO_CD = '0000' AND MENU_NM = N'사용자별메뉴관리' ), ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'저장' ), 4 );

--// MAP : 권한그룹-메뉴 ▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣
INSERT INTO CM_ROLEGRPMENU_MAP( SEQ, ROLEGRP_SEQ, MENU_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval, ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ), ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템사용자관리' ) );
INSERT INTO CM_ROLEGRPMENU_MAP( SEQ, ROLEGRP_SEQ, MENU_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval, ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ), ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'메뉴관리' AND UP_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템' AND UP_SEQ IS NULL ) ) );
INSERT INTO CM_ROLEGRPMENU_MAP( SEQ, ROLEGRP_SEQ, MENU_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval, ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ), ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'권한관리' ) );
INSERT INTO CM_ROLEGRPMENU_MAP( SEQ, ROLEGRP_SEQ, MENU_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval, ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ), ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'권한그룹관리' ) );
INSERT INTO CM_ROLEGRPMENU_MAP( SEQ, ROLEGRP_SEQ, MENU_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval, ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ), ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'권한그룹별메뉴관리' ) );
INSERT INTO CM_ROLEGRPMENU_MAP( SEQ, ROLEGRP_SEQ, MENU_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval, ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ), ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'사용자별메뉴관리' ) );

--// MAP : 권한그룹메뉴MAP-메뉴버튼 ▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템사용자관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'조회' ) --// 메뉴버튼_SEQ
  , '1'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템사용자관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'신규' ) --// 메뉴버튼_SEQ
  , '2'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템사용자관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'삭제' ) --// 메뉴버튼_SEQ
  , '3'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템사용자관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'저장' ) --// 메뉴버튼_SEQ
  , '4'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'메뉴관리' AND UP_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템' AND UP_SEQ IS NULL ) )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'조회' ) --// 메뉴버튼_SEQ
  , '1'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'메뉴관리' AND UP_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템' AND UP_SEQ IS NULL ) )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'신규' ) --// 메뉴버튼_SEQ
  , '2'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'메뉴관리' AND UP_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템' AND UP_SEQ IS NULL ) )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'삭제' ) --// 메뉴버튼_SEQ
  , '3'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'메뉴관리' AND UP_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'시스템' AND UP_SEQ IS NULL ) )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'저장' ) --// 메뉴버튼_SEQ
  , '4'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'권한관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'조회' ) --// 메뉴버튼_SEQ
  , '1'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'권한관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'신규' ) --// 메뉴버튼_SEQ
  , '2'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'권한관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'삭제' ) --// 메뉴버튼_SEQ
  , '3'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'권한관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'저장' ) --// 메뉴버튼_SEQ
  , '4'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'권한그룹관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'조회' ) --// 메뉴버튼_SEQ
  , '1'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'권한그룹관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'신규' ) --// 메뉴버튼_SEQ
  , '2'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'권한그룹관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'삭제' ) --// 메뉴버튼_SEQ
  , '3'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'권한그룹관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'저장' ) --// 메뉴버튼_SEQ
  , '4'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'권한그룹별메뉴관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'조회' ) --// 메뉴버튼_SEQ
  , '1'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'권한그룹별메뉴관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'신규' ) --// 메뉴버튼_SEQ
  , '2'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'권한그룹별메뉴관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'삭제' ) --// 메뉴버튼_SEQ
  , '3'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'권한그룹별메뉴관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'저장' ) --// 메뉴버튼_SEQ
  , '4'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'사용자별메뉴관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'조회' ) --// 메뉴버튼_SEQ
  , '1'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'사용자별메뉴관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'신규' ) --// 메뉴버튼_SEQ
  , '2'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'사용자별메뉴관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'삭제' ) --// 메뉴버튼_SEQ
  , '3'
);
INSERT INTO CM_ROLEGRPMENUBTN_MAP( SEQ, ROLEGRPMENUMAP_SEQ, MENUBTN_SEQ, DSP_SEQ ) VALUES( CM_ROLEGRPMENU_MAP_S.nextval
  , ( SELECT SEQ FROM CM_ROLEGRPMENU_MAP 
        WHERE ROLEGRP_SEQ = ( SELECT SEQ FROM CM_ROLEGRP_MGR WHERE ROLEGRP_NM = N'시스템관리그룹' ) 
          AND MENU_SEQ = ( SELECT SEQ FROM CM_MENU_MGR WHERE MENU_NM = N'사용자별메뉴관리' )
    )  --// 권한그룹메뉴MAP_SEQ
  , ( SELECT SEQ FROM CM_MENUBTN_MGR WHERE BTN_NM = N'저장' ) --// 메뉴버튼_SEQ
  , '4'
);

COMMIT;